baseURL = "https://koritek.org"
buildFuture = true
description = "A non-profit organization focusing on technology development and Soccer Training."
languageCode = "en-us"
theme = "koritek"
title = "Kominote Riral Teknoloji - KoRiTek"
[[menu.main]]
name = "Get Involved"
url = "/volunteer/"
weight = 5
[[menu.main]]
name = "Events"
url = "/events/"
weight = 4
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
[[menu.main]]
name = "Directors"
url = "/directors/"
weight = 2
[params]
cover = "img/haiti-kids-playing-with-fire-tv-tablet.jpg"
donateFooterText = "Want to make a difference in your community?"
donateMobileText = "Your donation to youth techonology and soccer training program will equip young individuals with both digital skills and physical prowess, offering a holistic approach to their development."
footerAbout = "KoRiTek is a 501(c)(3) non-profit organization. Donations and contributions are tax-deductible as allowed by law."
homeHeader = "Give the life of average youth a meaning in rural areas"
homeIntroHeader = "We empower students to reach their academic &amp; physical prowess and social potential."
homeIntroSummary = "<p>We anticipate that our youth technology students and soccer participants will engage passionately, embracing the opportunities to develop essential skills. Through interactive learning, they'll gain technological proficiency. In soccer, they'll cultivate teamwork and resilience, fostering personal growth. We're excited to witness their progress and see them flourish as confident individuals both in the digital world and on the field.</p> <p>Your donation to youth techonology and soccer training program will equip young individuals with both digital skills and physical prowess, offering a holistic approach to their development.</p>"
mission = "To give every student and everyone living in rural areas the opportunity to learn computer operations and take complete advantage of the technology."
volunteerButton = "Join us now"
volunteerHeader = "Koritek is about helping others"
volunteerSummary = "Learn how you can join us as a volunteer and make a difference in your community."
[permalinks]
posts = "/:year/:month/:title/"
projects = "/project/:filename/"
