baseURL = "https://koritek.org"
buildFuture = true
description = "A non-profit organization focusing on technology development and Soccer Training."
languageCode = "en-us"
theme = "koritek"
title = "Kominote Riral Teknoloji - KoRiTek"
[[menu.main]]
name = "Get Involved"
url = "/volunteer/"
weight = 5
[[menu.main]]
name = "Events"
url = "/events/"
weight = 4
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
[[menu.main]]
name = "Directors"
url = "/directors/"
weight = 2
[params]
cover = "img/haiti-kids-playing-with-fire-tv-tablet.jpg"
donateFooterText = "Want to make a difference in your community?"
donateMobileText = "Your donation to youth techonology and soccer training program will equip young individuals with both digital skills and physical prowess, offering a holistic approach to their development."
footerAbout = "KoRiTek is a 501(c)(3) non-profit organization. Donations and contributions are tax-deductible as allowed by law."
homeHeader = "Give the life of average youth a meaning in rural areas"
homeIntroHeader = "We empower students to reach their academic &amp; social potential."
homeIntroSummary = "<p>We want students to take advantage of the growing campaign in the use of Modern Technology in doing business to carve a niche for themselves and positively affecting their environment by training. This is as we also hope that the participants will also train and even employ others and as such cutting down the rate of unemployment in Haiti.</p> <p>Your donation provides access to technology and Internet to Haitian students who might otherwise go without.</p>"
mission = "To give every student and everyone living in rural areas the opportunity to learn computer operations and take complete advantage of the technology."
volunteerButton = "Join us now"
volunteerHeader = "Koritek is about helping others"
volunteerSummary = "Learn how you can join us as a volunteer and make a difference in your community."
[permalinks]
posts = "/:year/:month/:title/"
projects = "/project/:filename/"
