---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: content/directors
  label: Directors
  create: all
  match: "**/*"
  templates:
  - directors
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: document
  path: config.toml
  label: Config
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.46
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: '0.46'
